FROM codingcorp-docker.pkg.coding.net/registry/release/spin-base:1.0

COPY --from=fiat-compile /compiled_sources/fiat-web/build/install/fiat /opt/fiat
COPY --from=fiat-compile /compiled_sources/coding-deploy/config /opt/spinnaker/config

RUN adduser -D -S spinnaker
USER spinnaker

ENTRYPOINT ["/sbin/tini", "--", "/opt/fiat/bin/fiat"]
